song_lyrics = [
    "One love, one heart.",
    "Let's join together and feel alright.",
    "One love (oh Lord of mercy).",
    "One heart (I tell you).",
    "Let's join together (at this house I pray).",
    "And feel alright (and I will feel alright).",
    "Let's join together and feel alright.",
    "Let them all pass all their dirty remarks (one love).",
    "There is one question I'd really like to ask (one soul).",
    "Is there a place for the hopeless sinner.",
    "Who has hurt all mankind just to save his own.",
    "One love, one heart.",
    "Let's join together and feel alright.",
    "One love (hear my plea).",
    "One heart.",
    "Let's join together and feel alright.",
    "Let's join together (let's just trust in the Lord).",
    "And feel alright (and I will feel alright).",
    "Let's join together to fight this holy battle.",
    "So when the man comes there will be no no doom.",
    "Have pity on those whose chances grows thinner.",
    "There ain't no hiding place among the kingdoms of love yes.",
    "One love (hear my plea).",
    "One heart (oh).",
    "Let's join together and feel alright.",
    "One love (oh Lord of mercy).",
    "One heart (I tell you).",
    "Let's join together (let this house a pray).",
    "And feel alright (and I will feel alright).",
    "Let's join together and feel alright.",
    "One love, one heart.",
    "Let's join together and feel alright.",
    "One love (oh Lord).",
    "One heart (oh Lord).",
    "Let's join together and feel alright.",
    "Let's join together (let's all pray to the Lord).",
    "And feel alright (and I will feel alright).",
    "I tell you let them all pass all their dirty remarks (one love).",
    "There is one question I'd really like to ask (one soul).",
    "Is there a place for the hopeless sinner.",
    "Who has hurt all mankind just to save his own.",
    "One love (oh Lord of mercy).",
    "One heart (I tell you).",
    "Let's join together (at this house a pray).",
    "And feel alright (and I will feel alright).",
    "One love (hear my plea).",
    "One heart (hear my plea).",
    "Let's join together and feel alright (and I will feel alright).",
    "Let's join together (let's pray to the Lord).",
    "And feel alright (and I will feel alright)."
]